name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -ntp clean compile
    
    - name: Run tests
      run: mvn -ntp test
    
    - name: Package
      run: mvn -ntp package
    
    - name: Install plugin locally
      run: mvn -ntp install